# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libprotobuf-dev

# safelist
branches:
  only:
  - master

