# https://hub.docker.com/r/rocker/geospatial/tags
FROM rocker/geospatial:4.1.1
MAINTAINER Jonathan Callahan <jonathan@mazamascience.com>


# For MazamaSpatialUtils
RUN install2.r --error -r "https://cran.rstudio.com" \
    rmapshaper \
    MazamaSpatialUtils

# Add potentially useful spatial data for MazamaSpatialUtils 0.7.x
RUN mkdir -p /home/mazama/data/Spatial \
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/CA_AirBasins.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/CA_AirBasins_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/CA_AirBasins_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/EEZCountries.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/EEZCountries_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/EEZCountries_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/EPARegions.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/EPARegions_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/EPARegions_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/NWSFireZones.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/NWSFireZones_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/NWSFireZones_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/NaturalEarthAdm1.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/NaturalEarthAdm1_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/NaturalEarthAdm1_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/OSMTimezones.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/OSMTimezones_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/OSMTimezones_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/TMWorldBorders.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/TMWorldBorders_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/TMWorldBorders_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusCBSA.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusCBSA_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusCBSA_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusCounties.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusCounties_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusCounties_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusStates.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusStates_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/USCensusStates_05.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/WorldTimezones.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/WorldTimezones_02.rda
  && wget --directory-prefix /home/mazama/data/Spatial --no-host-directories --cut-dirs=2 http://data.mazamascience.com/MazamaSpatialUtils/Spatial_0.7/WorldTimezones_05.rda


