################################################################################
# Makefile for building and running docker containers


# OPERATIONAL version -------------------------------------------------------------
production_build:
	docker build --no-cache -t mazamascience/spatialutils:0.5.3 -t mazamascience/spatialutils:latest .

