################################################################################
# Makefile for building and running docker containers


# OPERATIONAL version -------------------------------------------------------------
production_build:
	docker build --no-cache -t mazamascience/spatialutils:0.6.0 -t mazamascience/spatialutils:latest .

