FROM mazamascience/spatialutils

RUN apt-get update \
  ### Install system libraries. Many more are installed due to dependencies
  && apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev \
    libssl-dev

## Install MazamaSpatialUtils from github
RUN installGithub.r \
     bart6114/jug

# jug instance configuration
ENV JUG_HOST 0.0.0.0
ENV JUG_PORT 8080

# jug app
COPY spatialUtilsApp.R .

EXPOSE 8080

CMD [ "Rscript", "spatialUtilsApp.R" ]

