#' @keywords locator
#' @export
#' @title Get PolygonID from SPDF of interest
#' @param SPDF SpatialPolygonsDataFrame of interest
#' @description Extracts the PolygonID column from the SPDF of interest initially generated by \code{organizePolygons()}
#' @return Vector of PolygonIDs
getPolygonID <- function(SPDF) {
    if(class(SPDF) != "SpatialPolygonsDataFrame") {
      stop(deparse(substitute(SPDF)), ' is not a SpatialPolygonsDataFrame.', call.=FALSE)
    } else {
    return(SPDF$polygonID)
    }
}
